apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "garden-util.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "garden-util.name" . }}
    helm.sh/chart: {{ include "garden-util.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "garden-util.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "garden-util.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: docker-config
          secret:
            secretName: builder-docker-config
            items:
              - key: .dockerconfigjson
                path: config.json
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
          volumeMounts:
            - name: docker-config
              mountPath: /root/.docker
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: proxy
          image: "gardendev/socat:0.1.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - TCP-LISTEN:5000,fork
            - TCP:{{ .Values.registry.hostname }}:5000
          ports:
            - name: proxy
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5000
          readinessProbe:
            tcpSocket:
              port: 5000
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
